### ISSUE TITLE
Card Background Colors

### ISSUE THREAD

**Issue by ShadowMole** [RowanACM/TeamLinguini#2]
Okay so I did some more formatting today.  The Card elements should have a background color that is the same as the header.  Cards also have 2 div elements inside.  A "left" div that will float on the left and contain an image of the person over their name.  Then there is a "descript" element that will float on the right side of the card and will be a description of the person.  For some reason, floating these 2 elements within the card is breaking the background color of the card, even though rest of the formatting is correct.  Commenting out only the left float, means that only the "left" element gets the correct color and the formatting is messed up. Commenting out only the right float, means entire Card gets the correct color, but the formatting is still not correct obviously.

**Comment by SirSaunders** [comment]
Try adding overflow:hidden to your card class.
https://stackoverflow.com/questions/944663/css-background-color-has-no-effect-on-a-div



Also instead of having 6 classes that altenating divs card1 card2 you can make 2 divs and remove the row div wrappers and float card1 div holding 3 cards right and card2 div float right holding the other 3 cards 

```
<div class="card1"  style="float:left">
    <div class="card>
    </div>
    <div class="card>
    </div>
    <div class="card>
    </div>
    </div
<div class="card2"  style="float:right">
    <div class="card>
    </div>
    <div class="card>
    </div>
    <div class="card>
    </div>
</div>
```

Just easier to follow. Later when we make it dynamically load we can make them inline so they will load in left to right and wrap.

**Comment by ShadowMole** [comment]
Okay, that makes sense.
